### PR TITLE
Build a pausable CPU.

### PR DESCRIPTION
**Pull request by zstewar1**
This new version of the cpu (gated behind feature `microcode`) uses a stack-based virtual machine to implement instructions. This makes it possible to pause instructions at various points in their execution, most importantly at yield points.

Essentially this makes it possible to have a state-machine for each instruction without customizing the state machine. Instead the state is "where in the microcode for this instruction am I?". Variables used by instructions are just stored on a stack, which turns out to work very well for most instructions!

The old CPU `tick` function is renamed to `run_single_instruction` to make it clearer that it always runs a whole instruction and uses `ctx.yield1m()` to perform concurrent processing. When using feature `microcode`, the `run_single_instruction` function remains available, but is implemented in terms of microcode. Whenver the microcode encounters a yield, `ctx.yield1m()` gets called automatically.

When using the `microcode` feature, a new `tick()` function is available which advances the CPU until the next yield, and a couple other ticking operations are possible.

If this CL is adopted fully, it will make the `ctx.yield1m()` function unnecessary.

Caveat emptor: The unit tests pass, but I haven't tried it against any real cartridges or against any of the test-roms which validate instructions. Or validate timing.

### CODE REVIEW

**Comment by ciaran2** [comment]
Not only does this perform well and not break any test ROMs, it actually fixes the instr_timing failure https://github.com/ciaran2/feo3boy/issues/27#issuecomment-1474744177

**Comment by zstewar1** [comment]
Did you test with `--features microcode`? If not, you're still running the direct executor.

I did discover a mistake in one of the timings and fixed it in both microcode and direct execution.

**Comment by ciaran2** [comment]
Ah, you're right, I forgot to do that. With the feature on intstr_timing now gives me this after the boot screen:
```
thread 'main' panicked at 'Cannot pop u8, microcode stack empty', feo3boy\src\gbz80core\microcode\impl.rs:43:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\feo3boy-player.exe -b gb_bios.bin -r test-roms/instr_timing/instr_timing/instr_timing.gb` (exit code: 101)
```

**Comment by zstewar1** [comment]
The microcodes should now all work and pass the cpu_instrs test. Didn't run the cpu timings test. Also rebased to current master.

**Pull request merged**
